### ISSUE TITLE
Register Top-level Namespace

### ISSUE THREAD

**Issue by Qiming-C** [CycloneDX/cyclonedx-property-taxonomy#10]
Hi CDX team, We would like to register top-level namespaces for `sonatype` . It will be used by the Lift project and administered by Lift maintainer. 
our public taxonomy link is here: https://help.sonatype.com/lift/open-source-vulnerability-analysis/dependency-view/cyclonedx-lift-namespace-taxonomy
Thank you for taking your time.

**Comment by stevespringett** [comment]
`sonatype` has been registered, however, I would recommend coordinating with other teams within Sonatype to ensure there isn’t property confusion within the namespace. Perhaps use `sonatype:lift` for Lift for example. FYI `sonatype:score` as documented https://help.sonatype.com/lift/open-source-vulnerability-analysis/dependency-view/cyclonedx-lift-namespace-taxonomy doesn’t make any sense as the spec can already represent this in a standardized way without the use of custom properties.

**Comment by Qiming-C** [comment]
by standardized way, you mean the `score`?

**Comment by stevespringett** [comment]
- Multiple ratings are supported, including scores, severity, etc. see https://github.com/CycloneDX/bom-examples/blob/master/VEX/vex.json for an example

**Comment by Qiming-C** [comment]
Thanks for the quick reply,  `sonatype:score` is different from these specs, we probably need to rename it to avoid some confusions
