### ISSUE TITLE
Request for the registration of a new top-level namespace "contact-software"

### ISSUE THREAD

**Issue by wenns** [CycloneDX/cyclonedx-property-taxonomy#100]
Dear all,

I would like to register a new top level namespace "cs" for our company CONTACT Software GmbH. 

We are an enterprize software vendor offering solutions around PLM (Product Livecycle Management), IIoT (Industrial Internet of Things) and Project Management. We are using SBOMs quite intensively and see some use cases for custom entities in them.

There is no taxonomy yet.

Thanks for your efforts; regards,
Waleri Enns

--
Waleri Enns
Head of Processes, Tools & Metrics

CONTACT Software GmbH
Wiener Straße 1–3, 28359 Bremen, Germany
T +49 421 20153-0
M +49 171 23456789
waleri.enns@contact-software.com
www.contact-software.com

Registered office: Bremen, Germany
Managing directors: Karl Heinz Zachries, Maximilian Zachries
Court of register: Amtsgericht Bremen HRB 39572

**Comment by jkowalleck** [comment]
feel free to pullrequest the needed changes to https://github.com/CycloneDX/cyclonedx-property-taxonomy/blob/main/README.md

**Comment by jkowalleck** [comment]
@wenns , 
please choose a namespae with more than 2 letters, to prevent confusions.

The same way `aquasecurity` was used instead of `as`,
you could use `contact-software` or something.

**Comment by wenns** [comment]
OK, I understand. What about "contact", then?

**Comment by jkowalleck** [comment]
> What about "contact", then?

high risk of confusion here.

what about "cslab"? I mean, this is the name of your org on github, right? 

there is no need to choose a short name or something. you could even go with "CONTACT Software GmbH" as a top level namespace.

**Comment by wenns** [comment]
All right, then we would like to reserve "contact-software".

**Comment by jkowalleck** [comment]
feel free to pullrequest the needed changes to https://github.com/CycloneDX/cyclonedx-property-taxonomy/blob/main/README.md

**Comment by jkowalleck** [comment]
hello @wenns , 

The reserved top level namespace `contact-software` exists for a while now, but the actual taxonomy was never linked here.
Could you check whether your taxonomy was published somewhere, and link it in the registry?
