### ISSUE TITLE
Applying a new top level namespace `bsi`

### ISSUE THREAD

**Issue by ThomSei** [CycloneDX/cyclonedx-property-taxonomy#102]
Dear CycloneDX Community,
as a representative of BSI, I would like to register the namespace ‘bsi’. The namespace should be in conjunction with BSI-TR-03183-2 (SBOM).
See https://bsi.bund.de/dok/TR-03183-en for details.

Best regards
Thomas Seider

**Comment by jkowalleck** [comment]
@ThomSei ,

please open a pullrequest with the needed changes to the registry.
