### ISSUE TITLE
Hoppr CDX Top-Level Namespace Request

### ISSUE THREAD

**Issue by lmco-ek** [CycloneDX/cyclonedx-property-taxonomy#13]
Request to register a TLN for `hoppr`.  For use by the Lockheed Martin Hoppr project.

Public docs for taxonomy: https://gitlab.com/lmco/hoppr/hoppr/-/blob/main/docs/architecture/cdx_taxonomy.md

Thanks!

**Comment by stevespringett** [comment]
hoppr namespace has been registered

**Comment by lmco-ek** [comment]
Awesome, thanks!
