### ISSUE TITLE
Finite State Namespace

### ISSUE THREAD

**Issue by njv299** [CycloneDX/cyclonedx-property-taxonomy#15]
This issue is a request to add a new top-level property namespace of `finitestate`. This namespace will be used to add custom properties containing values relevant to SBOMs produced by the Finite State firmware analysis platform.

For more company information, please see https://finitestate.io/

Thanks!

**Comment by coderpatros** [comment]
Hi @njv299, no problem. Do you have a link to documentation for the namespace available?

**Comment by njv299** [comment]
Unfortunately not yet, but it will be coming soon.

**Comment by njv299** [comment]
Here is a first cut at the documentation: https://github.com/FiniteStateInc/cyclonedx-property-taxonomy

Thanks again!

**Comment by coderpatros** [comment]
Done
