### ISSUE TITLE
Request for new top-level namespace: `gitlab`

### ISSUE THREAD

**Issue by Brcrwilliams** [CycloneDX/cyclonedx-property-taxonomy#16]
GitLab is working on creating a component inventory that is powered by CycloneDX SBoMs, which you can read more about at [Ingest SBoM Reports](https://gitlab.com/groups/gitlab-org/-/epics/8024). We'd like to register a new namespace to support this and any other integrations which we may build with CycloneDX.

You can find our taxonomy at https://gitlab.com/gitlab-org/security-products/gitlab-cyclonedx-property-taxonomy.

Thank you for all your work on CycloneDX!

**Comment by stevespringett** [comment]
Thanks @Brcrwilliams. The `gitlab` namespace has been registered. Huge thanks to GitLab for the support.
