### ISSUE TITLE
Request for new top level namespace `siemens` 

### ISSUE THREAD

**Issue by agschrei** [CycloneDX/cyclonedx-property-taxonomy#17]
Several teams across Siemens are working on tools that produce and/or consume CycloneDx SBOMs with some of these tools already seeing production use internally.  

We are using custom properties as part of this effort and would like to register our own `siemens` namespace that we can group these under.  

At present we cannot provide a publicly available taxonomy, but I will discuss making one available with the colleagues.  

Thanks to the entire CycloneDx team for all the effort that goes into this specification, it's been a big help!

**Comment by agschrei** [comment]
Linking @tngraf @tsjensen so they can vouch for this request being legitimate, since my account currently isn't associated with the siemens org on GitHub yet

**Comment by coderpatros** [comment]
Hi @agschrei, happy to reserve a namespace for Siemens.

Although they are intended for BOMs that are shared between parties. You can also use the `internal` namespace for custom properties that are only used internally.

**Comment by agschrei** [comment]
Hi @coderpatros, thank you for taking care of this, I appreciate it. 

Also, sincere apologies for not getting back to you sooner to give thanks, this got completely buried in my other notifications. 
I promise it's not for a lack of interest, we are currently doubling down on CycloneDx in our toolchains 😸

**Comment by coderpatros** [comment]
> Also, sincere apologies for not getting back to you sooner to give thanks, this got completely buried in my other notifications.

oh boy, I know what you mean about github notifications @agschrei
