### ISSUE TITLE
 Request for new sub level namespace `cdx:npm`

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-property-taxonomy#20]
currently working on https://github.com/CycloneDX/cyclonedx-node-npm
and found that some properties/evidences are not possible to model in existing CDX spec, as they are specific to _node/npm_. 

I would like to have an own namespace `cdx:npm` to make these properties part of generated CDX data.

**Comment by stevespringett** [comment]
Is “node” redundant?

**Comment by jkowalleck** [comment]
> Is “node” redundant?

you are right. 
changed all places from `node-npm` to `npm`
