### ISSUE TITLE
Veracode namespace

### ISSUE THREAD

**Issue by pdbm978** [CycloneDX/cyclonedx-property-taxonomy#23]
This issue is a request to add a new top-level property namespace of `veracode`. This namespace will be used to add custom properties containing values relevant to SBOMs produced by the Veracode's analysis platform. 

For more company information, please see https://github.com/veracode/cyclonedx-property-taxonomy. 

Thanks!

**Comment by stevespringett** [comment]
Thanks @pdbm978. The `veracode` namespace has been registered.
