### ISSUE TITLE
Add property to store the group of a dependency managed by Poetry

### ISSUE THREAD

**Issue by camillem** [CycloneDX/cyclonedx-property-taxonomy#26]
Hi,
(this is a followup to https://github.com/CycloneDX/cyclonedx-python/issues/374#issuecomment-1245157375)

It is common for dependency managers to implement a concept of categories corresponding to the different scenarios in which each dependency should be used. This information can be useful, for instance in a legal compliance analysis context.
Npm, for instance, has two categories: dependencies and Devdependencies, and those are already taken into account by CycloneDX:  
in is currently implemented with the property  [cdx:npm:package:development](https://github.com/CycloneDX/cyclonedx-property-taxonomy/blob/main/cdx/npm.md). 

For Poetry, it could be like the following: https://github.com/camillem/cyclonedx-property-taxonomy/blob/main/cdx/poetry.md

# `cdx:poetry` Namespace Taxonomy

| Namespace | Description |
| --------- | ----------- |
| `cdx:poetry:package` | Namespace for package specific properties. |

## `cdx:poetry:package` Namespace Taxonomy

| Property | Description |
| -------- | ----------- |
| `cdx:poetry:package:category` | The group of dependencies to which the package belongs, as described in https://python-poetry.org/docs/managing-dependencies/#dependency-groups. |

The property is named `category` and not `group` in order to be consistent with the content of the poetry.lock files.

At a later stage, it may be relevant to have a cross-package manager property of this kind.

Thanks,
Camille

**Comment by jkowalleck** [comment]
@approval from my side. 


re: "At a later stage, it may be relevant to have a cross-package manager property of this kind." 
I don't think this is needed here, as it is in the namespace for `poetry`. therefore, it is appears quite right.

**Comment by jkowalleck** [comment]
> As a a part of the CDX maintainers team, I will prepare a PR soon. It will basically be based on the work of @camillem's https://github.com/camillem/cyclonedx-property-taxonomy/blob/main/cdx/poetry.md

done that. see #29
