### ISSUE TITLE
request for top-level namespace: recon

### ISSUE THREAD

**Issue by jondot** [CycloneDX/cyclonedx-property-taxonomy#42]
Hi,
I'd like to request a new TLN: `recon`.
[Recon](https://github.com/rusty-ferris-club/recon) is a general purpose recon toolkit, with the upcoming ability to generate content SBOMs proofs. The taxonomy is still WIP (but can be looked at in the original project).

**Comment by coderpatros** [comment]
This has been reserved

**Comment by jkowalleck** [comment]
hello @jondot ,

The reserved top level namespace `recon` exists for a while now, but the actual taxonomy was never linked here.
Could you check whether your taxonomy was published somewhere, and link it in the registry?
