### ISSUE TITLE
Requesting registration of a new top level namespace: aboutcode

### ISSUE THREAD

**Issue by DennisClark** [CycloneDX/cyclonedx-property-taxonomy#47]
I am requesting registration of a new top level namespace,

Namespace: `aboutcode` 
Description: Namespace for use by AboutCode.org projects, including scancode-toolkit. 
Administered by: nexB
Taxonomy: https://github.com/nexB/aboutcode-cyclonedx-taxonomy 

We believe that the properties defined for this namespace are valuable for both the generation and consumption of CycloneDX-formatted SBOMs.

**Comment by jkowalleck** [comment]
Hello @DennisClark ,

I assume nexB will register further namespaces, eventually.
Therefore, I recommend registering the namespace `nexb`, instead of a separate namespace per product.
You can create sub-namespaces without further ado, like `nexb:aboutcode:my-property` or `nexb:scancode:foo`

What are your thoughts to that suggestion?

**Comment by DennisClark** [comment]
Hello @jkowalleck  

Thank you for your very thoughtful comments and suggestions.  I intend to create an issue in https://github.com/nexB/aboutcode-cyclonedx-taxonomy  to improve the README to clarify the role of AboutCode.org which has an info page at https://www.aboutcode.org/   

`[AboutCode](https://github.com/nexb/aboutcode) is a community of open source developers making open source easier to use by building open source tools for Software Composition Analysis (SCA). AboutCode is also the collective name for these SCA tools to discover, identify and track open source components.`   
and so forth. 

So even though nexB sponsors and leads the AboutCode projects, we would rather stick with the namespace of `aboutcode` , especially since one of our initiatives for 2023 is to establish common data structures and definitions in all of the active AboutCode projects.  

Your message indicates to me that we need to explain that more often and I plan to improve the taxonomy project README very soon.  

Best Regards,
Dennis Clark

**Comment by mjherzog** [comment]
To state it more simply: aboutcode is the top-level organization for all of nexB's open source projects.

**Comment by DennisClark** [comment]
Hello @jkowalleck  
Is there anything else needed from me to complete this registration request?

**Comment by jkowalleck** [comment]
nope. entry was proposed: https://github.com/CycloneDX/cyclonedx-property-taxonomy/pull/51 
waiting for triage
