### ISSUE TITLE
Registering a new top level namespace for Bosch Rexroth.

### ISSUE THREAD

**Issue by SpessartZiegler** [CycloneDX/cyclonedx-property-taxonomy#56]
Dear all,

in my role as Open Source Officer and Product Security Officer at Bosch Rexroth I would like to register a new top level namespace for Bosch Rexroth.

Namespace | Description | Administered By | Taxonomy

**rexroth | Namespace for use by Bosch Rexroth | Bosch Rexroth | RESERVED**

Before using the RESERVED namespace, I will document the taxonomy of the namespace and make publicly available.

Best Regards

Klaus Ziegler 
Engineering Excellence - processes, methods, tools DC/ENE1

Tel. +49 9352 18-6225
Fax +49 711 811-5171669
Mobil +49 152 22615021
Klaus.Ziegler3@boschrexroth.de
www.boschrexroth.com

Bosch Rexroth AG
Maria-Theresien-Straße 23
97816 Lohr am Main
GERMANY

Sitz: Stuttgart, Registergericht: Amtsgericht Stuttgart HRB 23192
Vorstand: Dr. Steffen Haack (Vorsitzender), Thomas Donato, Holger von Hebel, Reinhard Schäfer
Vorsitzender des Aufsichtsrats: Dr. Markus Forschner

**Comment by jkowalleck** [comment]
@SpessartZiegler 
feel free to pullrequest the needed change as soon as you have your taxonomy published.

**Comment by jkowalleck** [comment]
any update, @SpessartZiegler ?

**Comment by SpessartZiegler** [comment]
Not yet. I'm waiting for an internal approvement. I hope In can publish a taxanomy in October.

**Comment by jkowalleck** [comment]
if your internal processes are already kicked-off, it might be favorable putting your desired namespace as RESERVED.
Feel free to drop a pullrequest with the needed changes.
