### ISSUE TITLE
Request to Register amazon Top Level Namespace

### ISSUE THREAD

**Issue by jcburgo** [CycloneDX/cyclonedx-property-taxonomy#57]
We would like to request a new Top Level Namespace: 

Namespace: `amazon`
Description: Namespace for use by Amazon.
Administered By: Amazon
Taxonomy: `RESERVED` (Work in Progress)

**Comment by jcburgo** [comment]
Pull request: https://github.com/CycloneDX/cyclonedx-property-taxonomy/pull/58

**Comment by jcburgo** [comment]
Thanks!

**Comment by jkowalleck** [comment]
Hello @jcburgo,

The reserved top level namespace amazon exists for a while now, but the actual taxonomy was never linked here.
Could you check whether your taxonomy was published somewhere, and link it in the registry?
