### ISSUE TITLE
ByteTrail Namespace

### ISSUE THREAD

**Issue by b-grooters-byte** [CycloneDX/cyclonedx-property-taxonomy#62]
Request namespace for ByteTrail Fusion ecosystem

Name: bytetrail
Description: Namespace for use by ByteTrail 
Administered By: ByteTrail

**Comment by jkowalleck** [comment]
Do you have the taxonomy available already? 

If so, feel free to pullrequest a change to the `README.md`, and 
add your Top Level Namespace in alphabetical order in the table.

**Comment by b-grooters-byte** [comment]
we are still developing the namespace taxonomy for our products. Would need to be added once complete. Able to add without the taxonomy?

**Comment by jkowalleck** [comment]
Feel free to pullrequest for reserving the namespace.

https://github.com/CycloneDX/cyclonedx-property-taxonomy#registering-new-top-level-namespaces
> Before using your `RESERVED` namespace, documentation for the taxonomy of the namespace SHOULD be publicly available. Failure to do so MAY result in the namespace reservation being revoked.

**Comment by jkowalleck** [comment]
Hello @b-grooters-byte ,

The reserved top level namespace `bytetrail` exists for a while now, but the actual taxonomy was never linked here.
Could you check whether your taxonomy was published somewhere, and link it in the registry?
