### ISSUE TITLE
Add new top level namespace - ksoc

### ISSUE THREAD

**Issue by mateuszdyminski** [CycloneDX/cyclonedx-property-taxonomy#64]
Request namespace for KSOC Inc. ecosystem

Name: ksoc
Description: Namespace for use by KSOC Inc.
Administered By: KSOC
Taxonomy: https://github.com/ksoclabs/kbom/blob/main/docs/taxonomy.md

For now we would like to use `ksoc:kbom` namespace as this taxonomy is used by [kbom](https://github.com/ksoclabs/kbom) tool, but in the future we would like to extend it and use more generic `ksoc:`

**Comment by jkowalleck** [comment]
your taxonomy https://github.com/ksoclabs/kbom/blob/main/docs/taxonomy.md (#65) 
is bringing Kubernetes(`k8s`) to the table. 

The community is currently working on a general `k8s` related taxonomy. #59
To join efforts, instead of having everybody reinventing the wheel, I would like you to contribute to this, instead of pushing a 15th standard.  
[![xkcd standards](https://imgs.xkcd.com/comics/standards.png)](https://xkcd.com/927/)

How does this sound to you?

**Comment by mateuszdyminski** [comment]
> your taxonomy https://github.com/ksoclabs/kbom/blob/main/docs/taxonomy.md (#65) is bringing Kubernetes(`k8s`) to the table.
> 
> The community is currently working on a general `k8s` related taxonomy. #59 To join efforts, instead of having everybody reinventing the wheel, I would like you to contribute to this, instead of pushing a 14th standard. Maybe we can make it happen to have only one k8s taxonomy. Lets try :-) [![xkcd standards](https://camo.githubusercontent.com/a03b8f2e224d44e1a626c8288c03981d09788038f4b43c450a2de7d8df8d6ce0/68747470733a2f2f696d67732e786b63642e636f6d2f636f6d6963732f7374616e64617264732e706e67)](https://xkcd.com/927/)
> 
> How does this sound to you?

Of course we would like to contribute to to the `k8s` taxonomy. Our plan was to start from something and then iterate to the place where we can help to build `k8s` taxonomy. We have following plan:

- Add our own taxonomy prefix `ksoc` 
- Add support for CycloneDX in our KBOM tool - https://github.com/ksoclabs/kbom - based on existing `k8s` taxonomy
- Extend existing `k8s` taxonomy with custom fields - https://github.com/ksoclabs/kbom/blob/main/docs/taxonomy.md - still with `ksoc:kbom:` prefix
- If CycloneDX support in the `kbom` tool with our custom taxonomy will be warmly welcomed by the community we would like to add it to the https://github.com/CycloneDX/cyclonedx-property-taxonomy/issues/59

So answering your question - we don't want to reinvent the wheel, but rather build something internally, test, get feedback and discuss the standard with you

**Comment by jkowalleck** [comment]
hello @mateuszdyminski,


the previously linked `ksoc` docs were removed, due to https://github.com/CycloneDX/cyclonedx-property-taxonomy/pull/112
Could I ask you to pull-request an update?

**Comment by mateuszdyminski** [comment]
Sure thing! I'll do that tomorrow

**Comment by mateuszdyminski** [comment]
@jkowalleck

here is PR: https://github.com/CycloneDX/cyclonedx-property-taxonomy/pull/113
