### ISSUE TITLE
Proposal to implement Maven CycloneDX Property Taxonomy

### ISSUE THREAD

**Issue by karthika-g** [CycloneDX/cyclonedx-property-taxonomy#68]
Hi,

This is a proposal to add a new Namespace for Maven under cdx namespace.
For example something like `cdx:maven` similar to [npm](https://github.com/CycloneDX/cyclonedx-property-taxonomy/blob/main/cdx/npm.md).

With this a property to specify the scope of the dependency  `scope`. i.e https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#dependency-scope
which can be repreented as `cdx:maven:package:scope`

**Comment by jkowalleck** [comment]
@mr-zepol @stevespringett

**Comment by jkowalleck** [comment]
@hboutemy what is you opinion here?

**Comment by jkowalleck** [comment]
would somebody draft a pullrequest for the new namespace?
See the existing ones for examples: https://github.com/CycloneDX/cyclonedx-property-taxonomy/tree/main/cdx

we then could discuss changes and additions in the opened pulrequest.

**Comment by hboutemy** [comment]
We already have created a few properties in previous cyclonedx-maven-plugin without making them formal: I'll need to formalize existing ones
and new ones need to be created immediately in the official taxonomy
I'll have a look next week, I'm busy for now...

**Comment by jkowalleck** [comment]
Great. Looking forward to merging your pullrequest. :D

**Comment by jkowalleck** [comment]
see discussion here: https://github.com/CycloneDX/cyclonedx-property-taxonomy/pull/69

**Comment by jkowalleck** [comment]
I'll close this, as i see the original request being solved - a `cdx:maven` exists and can be improved - https://github.com/CycloneDX/cyclonedx-property-taxonomy/blob/main/cdx/maven.md

Thank you all for your work.
