### ISSUE TITLE
Add "scribe" namespace

### ISSUE THREAD

**Issue by ilans** [CycloneDX/cyclonedx-property-taxonomy#79]
Please add the "scribe" namespace for use by Scribe Security.
Administered By: https://scribesecurity.com

**Comment by jkowalleck** [comment]
@ilans , please pullrequest the needed changes.

**Comment by jkowalleck** [comment]
Hi @ilans ,

The reserved top level namespace `scribe` exists for a while now, but the actual taxonomy was never linked here.
Could you check whether your taxonomy was published somewhere, and link it in the registry?
