### ISSUE TITLE
Request for new top-level namespace registration `observer`

### ISSUE THREAD

**Issue by wallrat** [CycloneDX/cyclonedx-property-taxonomy#83]
This is a request to add the top-level namespace`observer` used by [SBOM Observer](https://sbom.observer) for metadata in exported SBOMs.

The initial taxonomy is [available](https://github.com/bitfront-se/cyclonedx-property-taxonomy) and in active use.

Will follow up this issue with a PR for the requested addition. 

Please let me know if there is any additional information needed.

Regards,
Andreas Bielk / andreas@sbom.observer

**Comment by jkowalleck** [comment]
see https://github.com/bitfront-se/cyclonedx-property-taxonomy
