### ISSUE TITLE
Request for new top level namespace (soos)

### ISSUE THREAD

**Issue by SOOS-JJennings** [CycloneDX/cyclonedx-property-taxonomy#97]
Hi,

SOOS would like to request a new top-level property namespace of "soos". We currently ingest and produce CycloneDX SBOMs and are anticipating the need to enrich these with additional properties.

Our shell property taxonomy docs can be found here: https://github.com/soos-io/cyclonedx-property-taxonomy

If there are any additional details you need please let me know.

Thanks,
Josh Jennings

**Comment by jkowalleck** [comment]
@SOOS-JJennings, please open a pullrequest with the needed modifications on <https://github.com/CycloneDX/cyclonedx-property-taxonomy/blob/main/README.md#registered-top-level-namespaces>.
